### ISSUE TITLE
make build-release does not work

### ISSUE THREAD

**Issue by regul4rj0hn** [inadarei/justgo-microservice#6]
## Summary / Context
When using justgo to create a new microservice from scratch the `make build-release` command does not work.

## Expected Behavior
The `make build-release` command should build a working release image that can be run with `make run-release`

## Current Behavior
First of all, in order to build a release image a valid initialized git repository, with at least one commit is required. 
While this is obvious if you look at the makefile or try to run the command, it is not explicit in the documentation.
Even after remediating that, the `make build-release` command fails with:
```
$ make build-release                                                                                                                                                       4ms 811µs
docker build --target release -t local/ms-demo-golang:0fa0ca218fdd65f078bf68db1a88dab288b4f2c1 .
[+] Building 32.1s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 1.11kB                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 113B                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/golang:1.12-alpine3.9                                                                                                                                      2.9s
 => [auth] library/golang:pull token for registry-1.docker.io                                                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                                             0.0s
 => => transferring context: 39.67kB                                                                                                                                                                          0.0s
 => CACHED [builder 1/4] FROM docker.io/library/golang:1.12-alpine3.9@sha256:03b3b1d0fc2ca786fd4342967f3fb3b66215def8a0c3701301a6d0a94d8bfa86                                                                 0.0s
 => [builder 2/4] COPY . /app                                                                                                                                                                                 0.0s
 => [builder 3/4] WORKDIR /app                                                                                                                                                                                0.1s
 => [builder 4/4] RUN adduser -s /bin/false -D appuser  && echo "Installing git and bash support"  && apk update && apk upgrade  && apk add --no-cache bash git  && echo "Installing code hot reloader"  &&  28.9s
 => ERROR [release 1/2] COPY --from=builder /go/src/app/main .                                                                                                                                                0.0s
------
 > [release 1/2] COPY --from=builder /go/src/app/main .:
------
failed to compute cache key: failed to walk /var/lib/docker/tmp/buildkit-mount023630495/go/src/app: lstat /var/lib/docker/tmp/buildkit-mount023630495/go/src/app: no such file or directory
make: *** [Makefile:50: build-release] Error 1
```

## Steps
1. With justgo installed,  run `justgo test` to create a new test microservice and `cd test`
2. Run `git init` and `git add . && git commit -m "initial commit"`
3. Run `make build-release`
The docker image will fail to build

## Suggestions for Solution
Not a docker expert but it seems something is off with the COPY command

**Comment by inadarei** [comment]
Thank you for reporting the issue. Will investigate. Can you share the details of your environment? Operating system, docker version + how it is installed.

**Comment by regul4rj0hn** [comment]
Certainly, I'm running the tests on Windows 10 in an Arch Linux WSL2 install, and Docker Desktop v20.10.5.
I will attempt to test on a Mac tomorrow and let you know how it goes. I don't trust the WSL install.
Thanks for the prompt response!

**Comment by inadarei** [comment]
This should be fixed. List of all fixes:

1. Fixed bugs with build and release stages
2. Removed necessity for the project to be under git, unless you are building a release or running a release.
3. Added documentation for build-release and run-release, stating that those stages do require the project to be under git (since they use last-commit hash)

**Comment by regul4rj0hn** [comment]
That's great! I will give it a go as soon as I can. Thanks, man!

**Comment by inadarei** [comment]
Thank you!

**Comment by regul4rj0hn** [comment]
Sorry that I just got back to this. The build worked like a charm on both Windows WSL and MacOS hosts. 
On top of that, the resulting release image built from scratch is ~10MB, impressive! 
Thanks a lot for your help, @inadarei I will make sure to contribute if I find anything else I can help with.

**Comment by inadarei** [comment]
Fantastic! Thank you for finding and reporting the problem. Glad to hear fix worked well
